export enum MessageType {
  FETCH_OPTIONS = 'FETCH_OPTIONS',
  OPTIONS_RESULT = 'OPTIONS_RESULT',
  FETCH_PAGE = 'FETCH_PAGE',
  PAGE_RESULT = 'PAGE_RESULT',
  FETCH_PROJECTS = 'FETCH_PROJECTS',
  PROJECTS_RESULT = 'PROJECTS_RESULT',
  SAVE_AS = 'SAVE_AS',
  LOAD = 'LOAD',
  ACK = 'ACK'
}